### ISSUE TITLE
FeedManager.Poll should have a configurable interval

### ISSUE THREAD

**Issue by nickmonad** [hackbg/terra-fm-metrics-exporter#2]
https://github.com/hackbg/terra-fm-metrics-exporter/blob/main/manager/manager.go#L160

Small issue, but it would be nice to have this ticker interval as a configurable value via an environment variable, `FEED_POLL_INTERVAL` or something like that. Ideally, it would support intervals like `30s`, `5m`, etc

**Comment by denismaxim0v** [comment]
resolved with #3
